import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useAuth } from "@/context/authcontext";
import AuthButton from "@/components/authbutton";

// import { loadEntrys } from "../lib/load-posts";

import Announcement from "@/components/announcement";
import Feed from "@/components/feed";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home({ posts }) {
  const { isLoggedIn } = useAuth();

  return (
    <>
      <Head>
        <title>Sesac Community</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Announcement></Announcement>
        <Feed posts={posts}></Feed>
        {/* <Link href="/feed">feed test</Link> */}
      </section>
      <div>
        <h1>{isLoggedIn ? "You are logged in!" : "You are not logged in."}</h1>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://127.0.0.1:8000/post");
  const posts = await res.json();

  return {
    props: {
      posts,
    },
  }
}
