import Head from "next/head";
import Feed from "@/components/feed";

export default function Search({ posts }) {

  return (
    <>
      <Head>
        <title>{query} - Community CMS Search!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Feed
          posts={posts}
        ></Feed>
      </section>
    </>
  );
}
