import Head from "next/head";

export default function Settings() {
  return (
    <>
      <Head>
        <title>Settings Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Hello Settings</p>
      <p>Delete Account</p>
    </>
  );
}
