import React, { useState, FormEvent } from "react";
import Head from "next/head";
import Editor from "@/components/editor/editor";
import EditorTitle from "@/components/editor/editortitle";
import EditorContent from "@/components/editor/editorcontent";
import { useRouter } from "next/router";

export default function Page() {
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const router = useRouter();

  async function createPost(e) {
    e.preventDefault();
    const post = {
      title,
      content,
      author: undefined,
      date: new Date(),
    };

    try {
      // const formData = new FormData(event.currentTarget);
      const response = await fetch("http://localhost:8000/submit", {
        method: "POST",
        body: JSON.stringify(post),
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: "include",
      });

      if (!response.ok) {
        throw new Error("Failed to submit data. Please try again");
      }

      router.push("/");

    } catch (error) {
      console.error(error);
    } finally {
    }
  }

  return (
    <>
      {/* {error && <div style={{ color: "red "}}>{error}</div>} */}
      <Head>
        <title>Submit to Sesac Community</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Editor onSubmit={createPost}>
        <EditorTitle title={title} setTitle={setTitle}></EditorTitle>
        <EditorContent content={content} setContent={setContent}></EditorContent>
      </Editor>
    </>
  );
}
