import Head from "next/head";
import Link from "next/link";

import Entry from "@/components/entry";

export default function Post({ post }) {
  return (
    <>
      <Head>
        <title>{post.title} : Community Sesac</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Entry post={post}></Entry>
    </>
  );
}

export async function getStaticPaths() {
  const res = await fetch(`http://localhost:8000/post`);
  const posts = await res.json();

  const paths = posts.map((post) => {
      return {
          params: { pid: post.id.toString() },
      };
  });

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const res = await fetch(`http://localhost:8000/post/${params.pid}`);
  const post = await res.json();

  return { props: { post }, };
}
