import { useRouter } from "next/router";

import { dataPosts } from "@/models/postsdata";
import Head from "next/head";
import Link from "next/link";

export default function Post({ post }) {
  // const router = useRouter();
  // return <p>Post: {router.query.slug}</p>
  return (
    <>
      <Head>
        <title>Title : Community CMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <p>hello post</p>
        {/* <Header author={post.author} date={post.date}></Header>
        <Content h={post.h} content={post.content}></Content> */}
      </article>
    </>
  );
}

function Header({ author, date }) {
  return (
    <section></section>
  );
}

/* export async function getStaticPaths() {
//     const res = await fetch(``);
//     const posts = await res.json();


  const posts = dataPosts;
  const paths = posts.map((post) => {
      return {
          params: {pid: post.pid.toString() },
      };
  });

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  // const res = await fetch(``);
  // const post = await res.json();
  const post = dataPosts.find((post) => post.pid === params.pid);
  // const post = dataPosts[params.id];

  // const posts = JSON.parse(JSON.stringify(dataPosts));

  return { props: { post }, };
} */

function Content({h, content}) {
  return (
    <section>
      <h2>{h}</h2>
      {content}
    </section>
  );
}

function Credit({author, date}) {
  const postTime = new Date(date);
  const currenTime = new Date();
  const diff = (currenTime - postTime)/(1000*60*60*24);
  return (
    <>
      <span slot="authorName">{author}</span>
      <span slot="separator"> </span>
      {/* <time dateTime={date}>{diff}</time> */}
      <time dateTime={date}>{date}</time>
    </>
  );
}
